name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs when you push to the 'main' branch
  pull_request:
    branches:
      - main  # Runs for pull requests targeting the 'main' branch

jobs:
  # Job to test the application
  test:
    runs-on: ubuntu-latest  # Use Ubuntu runner for the job
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python version
        with:
          python-version: '3.9'  # Specify the version of Python to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover tests/  # Discover and run tests in the 'tests' directory

